# Generated by Django 4.2.2 on 2023-06-30 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("onlinecourse", "0002_choice_submission_question_choice_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="question",
            name="lesson",
        ),
        migrations.AddField(
            model_name="question",
            name="courses",
            field=models.ManyToManyField(to="onlinecourse.course"),
        ),
        migrations.AddField(
            model_name="question",
            name="marks",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="submission",
            name="date_submitted",
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="submission",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="choice",
            name="is_correct",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="onlinecourse.question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.CharField(
                default="This is a sample question.", max_length=500
            ),
        ),
    ]
